name: suzanne_podcast_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  iconsax: ^0.0.8
  dio: ^5.7.0
  youtube_player_flutter: ^9.1.1
  shimmer: ^3.0.0
  table_calendar: ^3.1.3  # Downgrade here
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.4.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.2
  just_audio: ^0.9.44
  video_player: ^2.9.2
  youtube_explode_dart: ^2.3.9
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_messaging: ^15.2.2
  firebase_analytics: ^11.4.2
  flutter_local_notifications: ^18.0.1
  intl: ^0.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/onboarding/
    - assets/logo/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic  



 

                