name: suzanne_podcast_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  iconsax: ^0.0.8
  dio: ^5.7.0
  youtube_player_flutter: ^9.1.1
  shimmer: ^3.0.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/onboarding/
    - assets/logo/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic  






                